### ISSUE TITLE
tslint: how can i use tslint with output format "verbose"

### ISSUE THREAD

**Issue by bobby1991qw** [jpavon/react-scripts-ts#10]
I add option below:
`linterOptions: {
    format: 'verbose'
}`

and restart project. But get error `./src/App.tsx(22,5): Calls to 'console.log' are not allowed.`

**Comment by jpavon** [comment]
@bobby1991qw you need to add the rule "no-console" to tslint.json https://github.com/jpavon/react-scripts-ts/blob/master/template/tslint.json
