### ISSUE TITLE
class properties babel transform

### ISSUE THREAD

**Issue by Kerumen** [jpavon/react-scripts-ts#14]
I wanted to switch to this project but I can't because we are using class properties and I have this error when I launch our project.

> Support for the experimental syntax 'classProperties' isn't currently enabled (77:9)

I see 2 solutions here:

- As this is a pretty common syntax now, add `"@babel/plugin-proposal-class-properties"` in the list of babel [plugins](https://github.com/jpavon/react-scripts-ts/blob/master/config/webpack.base.js#L95)
- [Here](https://github.com/jpavon/react-scripts-ts/blob/master/config/webpack.base.js#L93) set to `true` to allow users to add custom `.babelrc` in their project to extend the config.

What do you prefer @jpavon?

**Comment by jpavon** [comment]
@Kerumen added `babelrc: true` in the latest version

**Comment by Kerumen** [comment]
@jpavon Thanks!
