### ISSUE TITLE
Not an issue... just want to say, this project is awesome.

### ISSUE THREAD

**Issue by edpark11** [jpavon/react-scripts-ts#7]
I wanted to upgrade to webpack 4. Tried CRA 2.0, but rewiring in CRA 2.0 was super-painful.

Tried this. Build times were much faster than react-scripts-ts (by about 50%) and much much faster than CRA 2.0 (by about 60-70%). Also, importantly, the original react-app-rewired works fine with this (don't need to do any of the crazy things required by the new CRA 2.0 configuration).

Anyways, just wanted to add a note of appreciation to you guys.

**Comment by jpavon** [comment]
Thanks @edpark11, compilation speed was one of my goals with this project, I should probably add it to the readme.
